.Preface

This OGC Community Standard was an outcome of a European Union project, "Maximizing the Exploitation of Linked Open Data in Enterprise and Science" (MELODIES), run from 2013 to 2016, and released under a Creative Commons 4.0 Licence by the University of Reading.

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[security]
[[security_considerations]]
== Security Considerations

Given the intended use case of downloading data to a browser, there is no functionality within this specification to facilitate authenticity, integrity and confidentiality (e.g. signatures or encryption). This can be applied at the transport level using standards that apply there. Use cases involving authenticity, integrity and confidentiality outside of the transport context (e.g. offline devices) are not intended or supported.

[abstract]
[[abstract]]
== Abstract

Based on JavaScript Object Notation (JSON), CoverageJSON is a format for publishing spatiotemporal data to the Web. The primary design goals are simplicity, machine and human readability and efficiency. While other use cases are possible, the primary CoverageJSON use case is enabling the development of interactive visual websites that display and manipulate environmental data within a web browser.

Implementation experience has shown that CoverageJSON is an effective, efficient format, friendly to web and application developers, and therefore consistent with the current https://ogcapi.ogc.org/[OGC API developments]. CoverageJSON supports the efficient transfer from big data stores of useful quantities of data to lightweight clients, such as browsers and mobile applications. This enables straightfoward local manipulation of the data, for example, by science researchers. Web developers often use and are familiar with JSON formats.

CoverageJSON can be used to encode coverages and collections of coverages. Coverage data may be gridded or non-gridded, and data values may represent continuous values (such as temperature) or discrete categories (such as land cover classes). CoverageJSON uses JSON-LD to provide interoperability with RDF and Semantic Web applications and to reduce the potential size of the payload.

Relatively large datasets can be handled efficiently in a “web-friendly” way by partitioning information among several CoverageJSON documents, including a tiling mechanism. Nevertheless, CoverageJSON is not intended to be a replacement for efficient binary formats such as NetCDF, HDF or GRIB, and is not intended primarily to store or transfer very large datasets in bulk.

The simplest and most common use case is to embed all the data values of all variables in a Coverage object within the CoverageJSON document, so that it is "self-contained". Such a standalone document supports the use of very simple clients.

The next simplest use case is to put data values for each variable (parameter) in separate array objects in separate CoverageJSON documents which are linked from the Coverage object. This is useful for a multi-variable dataset, such as one with temperature, humidity, wind speed, etc., to be recorded in separate files. This allows the client to load only the variables of interest.

A sophisticated use case is to use tiling objects, where the data values are partitioned spatially and temporally, so that a single variable’s data values would be split among several documents. A simple example of this use case is encoding each time step of a dataset into a separate file, but the tiles could also be divided spatially in a manner similar to a tiled map server.

[keywords]
[[keywords]]
== Keywords

The following are keywords to be used by search engines and document catalogues:

ogcdoc, OGC Document, JSON, JSON-LD, CoverageJSON, CovJSON, Coverage, spatiotemporal, linked data.

[source]
[[source_of_this_document]]
== Source of this document

The majority of the content in this OGC document is a direct copy of the content originally contained at https://github.com/covjson/specification. No normative changes have been made to the content. This OGC document does contain content not in the original source CoverageJSON GitHub repository. Specifically, while derived from content of the original CoverageJSON repository, the Abstract, Keywords, Preface, Security Considerations, Submitting Organizations, Endorsers, Terms and Definitions, and References sections and Annex B (Bibliography) in this document are not found in the original CoverageJSON repository.

The future community web site and source repository will contain the OGC version.

[Validity]
[[validity_of_content]]
== Validity of content

The Submission Team has reviewed and certified that the snapshot content in this Community Standard is true and accurate. The snapshot for OGC CoverageJSON Version 1.0 was taken on December 2021 from the https://github.com/covjson/specification[CovJSON Version 0.2 GitHub Repository].

[[submitting_organisations]]
== Submitting Organisations

* UK Met Office
* University of Reading
* Meteorological Service of Canada
* Unidata UCAR
* US NWS/NOAA
* ESIP/JPL/NASA

[[submitters]]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

* Chris Little    (editor)        UK Met Office
* Jon Blower      (editor)        University of Reading
* Maik Riechert   (editor)        University of Reading
* Tom Kralidis    (contributor)   Meteorological Service of Canada
* Ethan Davies    (contributor)   Unidata UCAR
* Steve Olson     (contributor)   US NWS/NOAA
* Lewis McGibbney (contributor)   ESIP/JPL/NASA

[.preface]
== Acknowledgements

This work was inspired by a demonstration of the concept by Joan Masó of CREAF.
