== Scope 

This OGC Community Standard is a logical implementation of the long-established abstract conceptual standard ISO19123:2005 (also known as OGC Abstract Topic 6). The original CoverageJSON specification has been stable for several years, with a wide-spread international implementation community in the environmental sciences. The current version of the open specification, available on https://github.com/covjson/specification[original GitHub], is labelled ‘V0.2-draft’. This version is the basis of this Community Standard with only editorial changes for presentation.

A formal JSON schema has been added for all the JSON objects identified, so that conformance to the OGC Community Standard can be checked. 

Unused or imprecisely specified components have been removed.

Future work have been identified, such as the use of multiple time dimensions, or to use JSON-LD V1.1.

This specification does not specify encoding of information in any format other than JSON https://datatracker.ietf.org/doc/html/rfc7159[IETF RFC 7159].

