This is a list of all the assertions in the ISO19123-1 (2007), also known as OGC07-001 Abstract Specification 
Topic 6: Schema for coverage geometry and functions.

== ISO19123:2005 / Abstract Spec Topic 6 extracts

=== Introduction
Coverage is a subtype of feature

Coverage is a feature that has multiple values for each attribute type

Each direct position within the geometric representation of the feature has a single value for each attribute type

The same phenomenon may be represented as either a discrete feature or a coverage

Coverage can be derived from a collection of discrete features with common attributes

Values of the coverage at each position being the values of the attributes of the feature located at that position

=== Scope
Coverages support mapping from a spatial, temporal or spatiotemporal domain to feature attribute values where feature attribute types are common to all geographic positions within the domain

Coverage domain consists of a collection of direct positions in a coordinate space that may be defined in terms of up to three spatial dimensions as well as a temporal dimension

Defines the relationship between the domain of a coverage and an associated attribute range

Characteristics of the spatial domain are defined 

Characteristics of the attribute range are not part of this standard

=== Conformance
Specifies interfaces for several types of coverage objects

Supports the interchange of coverage data independently of those interfaces 

Two sets of conformance classes: one for implementation of the interfaces, the other for the exchange of coverage data

Simple coverage interface A.1.1 

Discrete coverage interface A.1.2 

Discrete coverage interchange A.2.1

Interface conformance classes require implementation of all attributes, associations and operations of relevant classes

Single conformance class (A.2.1) that supports a simple interface for evaluation of any coverage type, but exposes none of the internal structure of the coverage

Conformance classes that support interfaces to specific coverage types that expose additional information about the internal structure of the coverage

=== Normative references 
ISO/TS 19103:2005, Geographic information — Conceptual schema language 

ISO 19107:2003, Geographic information — Spatial schema 

ISO 19108:2002, Geographic information — Temporal schema 

ISO 19109:2005, Geographic information — Rules for application schema 

ISO 19111:2003, Geographic information — Spatial referencing by coordinates 

ISO 19115:2003, Geographic information — Metadata 

=== Terms, definitions, abbreviated terms and notation
Continuous coverage returns different values for the same feature attribute at different direct positions within a single spatial object, temporal object or spatiotemporal object in its domain

Coverage: feature that acts as a function to return values from its range for any direct position within its spatial, temporal or spatiotemporal domain

Discrete coverage returns the same feature attribute values for every direct position within any single spatial object, temporal object or spatiotemporal object in its domain 

Domain of a discrete coverage consists of a finite set of spatial, temporal, or spatiotemporal objects

=== Fundamental characteristics of coverages 
Coverage is a feature that associates positions within a bounded space (its domain) to feature attribute values (its range)

Coverage is both a feature and a function

Coverage may represent a single feature or a set of features

coverage domain is a set of geometric objects described in terms of direct positions

Coverage subtypes may be defined in terms of their domains

Coverage domain can contain overlapping geometric objects

Range of a coverage is a set of feature attribute values

Range of a coverage may be either a finite or a transfinite set

Value set is represented as a collection of records with a common schema

Feature attribute value may be of any data type

Inverse evaluation is the calculation and exposure of a set of geometric objects associated with specific values of the attribute

Inverse evaluation may return many geometric objects associated with a single feature attribute value

Discrete coverage has a domain that consists of a finite collection of geometric objects and the direct positions contained in those geometric objects

Discrete coverage maps each geometric object to a single record of feature attribute values

Geometric object and its associated record form a geometry value pair

Discrete coverage may be represented as a collection of ordered pairs of independent and dependent variables

Each independent variable is a geometric object and each dependent variable is a record of feature attribute values

Continuous coverage has a domain that consists of a set of direct positions in a coordinate space  

Continuous coverage maps direct positions to value records

=== Coverage Core
CV_Coverage shall support three attributes, five operations, and three associations.

==== 1.1 Attributes:
  *domainExtent* shall contain the extent of the domain of the coverage. The data type EX_Extent is defined in ISO 19115:2003. Extents may be specified in space, time or space-time. 
  *rangeType* A simple list is the most common form of rangeType, but RecordType can be used recursively to describe more complex structures. The rangeType for a specific coverage shall be specified in an application schema
  *commonPointRule*  identifies the procedure for evaluating the Coverage at a position that falls either on a boundary between geometric objects or within the boundaries of two or more overlapping geometric objects

==== 1.2 Operations:
  *List* returns all objects with their attribute values. Returns null for analytic coverages
  *Select* filters returned values by geometry and time. Returns null for analytic coverages
  *Find* returns the n nearest objects and their attribute values. Returns null for analytic coverages
  *Evaluate* returns specified attribute values for a specified direct position
  *EvaluateInverse* returns a set of objects for a specified set of attributes

==== 1.3 Associations:
  *CRS*
  *Domain*
  *Range*
  
Coverage: any data representation that assigns values directly to spatio-temporal position. 

A coverage is a function from a spatial, temporal or spatiotemporal domain to an attribute range. 

A coverage associates a position within its domain to a record of values of defined data types.

A coverage is a mapping from a spatial, temporal or spatiotemporal domain to attribute values sharing the same type within the domain.

This document defines the relationship between the domain of a coverage and an associated attribute range. 

The characteristics of the domain are defined whereas the characteristics of the attribute range are not part of this standard.

Coverage: feature that acts as a function to return values from its range for any direct position within its domain

A coverage conceptually can be viewed as a function which, for every value of its domain set, provides a particular value taken from its range set; actually, a coverage may provide a set of values for a particular position.

Coordinates in a coverage are all expressed in one and the same Coordinate Reference System (CRS), its Native CRS.

Different views on this coverage concept exist.

While in general more than one value can be returned for a particular Direct Position, sometimes exactly one  value will be delivered.

The Domain Set of a coverage, as described by its Coordinate Reference System (CRS) consists of a number vof axes which together define some n-dimensional space, with n>0. 

Axes can represent alternate representations of coordinate measurements.

Axes, without any spatial nor temporal semantics, might be called “abstract”.

The range of CRSs to be used is open-ended; CRSs not described nor mentioned in this standard might be used

In a coverage, the domain and range sets may be organised in different ways, driven by practical considerations.

Some realization alternatives; concrete standards may or may not adopt these (Coverage by Partitioning, by Domain&Range, by Function), and may provide further ones

  
