This is a list of all the assertions in the ISO19123-1 (2007), also known as OGC07-001 Abstract Specification 
Topic 6: Schema for coverage geometry and functions.

== ISO19123:2005 / Abstract Spec Topic 6 extracts

Coverage  is  a  subtype  of  feature
Coverage  is  a  feature  that  has  multiple values  for  each  attribute  type
Each  direct  position  within  the  geometric  representation  of  the  feature has a single value for each attribute type.

Coverage: feature that acts as a function to return values from its range for any direct position within its spatial, temporal or spatiotemporal domain.

=== 1. CV_Coverage shall support three attributes, five operations, and three associations.

==== 1.1 Attributes:
  *domainExtent* 
  *rangeType* A  simple  list  is  the  most common  form  of rangeType,  but  RecordType  can  be  used  recursively  to describe  more  complex  structures. The rangeType for a specific coverage shall be specified in an application schema.
  *commonPointRule*  identifies the procedure for evaluating the Coverage at a position that falls either on a boundary between geometric objects or within the boundaries of two or more overlapping geometric objects

==== 1.2 Operations:
  *List* returns all objects with their attribute values. Return null for analytic coverages.
  *Select* filters returned values by geometry and time. Returns null for analytic coverages.
  *Find* returns the n nearest objects and their attribute values. Returns null for analytic coverages.
  *Evaluate* returns specified attribute values for a specified direct position
  *EvaluateInverse* returns a set of objects for a specified set of attributes.

==== 1.3 Associations:
  *CRS*
  *Domain*
  *Range*
  
Coverage: any data representation that assigns values directly to spatio-temporal position. 
A coverage is a function from a spatial, temporal or spatiotemporal domain to an attribute range. 
A coverage associates a position within its domain to a record of values of defined data types.
A coverage is a mapping from a spatial, temporal or spatiotemporal domain to attribute values sharing the same type within the domain.
This document defines the relationship between the domain of a coverage and an associated attribute range. 
The characteristics of the domain are defined whereas the characteristics of the attribute range are not part of this standard.
Coverage: feature that acts as a function to return values from its range for any direct position within its domain
A coverage conceptually can be viewed as a function which, for every value of its domain set, provides a particular value taken from its range set; actually, a coverage may provide a set of values for a particular position.
Coordinates in a coverage are all expressed in one and the same Coordinate Reference System (CRS), its Native CRS.
Different views on this coverage concept exist.
While in general more than one value can be returned for a particular Direct Position, sometimes exactly one  value will be delivered.
The Domain Set of a coverage, as described by its Coordinate Reference System (CRS) consists of a number vof axes which together define some n-dimensional space, with n>0. 
Axes can represent alternate representations of coordinate measurements.
Axes, without any spatial nor temporal semantics, might be called “abstract”.
The range of CRSs to be used is open-ended; CRSs not described nor mentioned in this standard might be used
In a coverage, the domain and range sets may be organised in different ways, driven by practical considerations.
Some realization alternatives; concrete standards may or may not adopt these (Coverage by Partitioning, by Domain&Range, by Function), and may provide further ones

  
