[big]*i.     Abstract*

CoverageJSON is a geospatial coverage interchange format based on JavaScript Object Notation (JSON)

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document, JSON, CoverageJSON, CovJSON, Coverage

[big]*iii.   Preface*

[NOTE]
====
Insert Preface Text here. Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work. >
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====
[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

UK Met Office (Technical Member)

University of Reading (Associate/University Member) 

Meteorological Service of Canada (Associate Member)

Unidata UCAR (Technical Member)

US NWS/NOAA (Principal Member)

ESIP/JPL/NASA (Strategic Member)

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editor or the submitters:

Chris Little    UK Met Office 

Jon Blower      University of Reading 

Tom Kralidis    Meteorological Service of Canada 

Ethan Davies    Unidata UCAR 

Steve Olson     US NWS/NOAA 

Lewis McGibbney ESIP/JPL/NASA 

