== References
The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

[NOTE]
====
https://covjson.org/spec 

OGC07-011, Abstract Specification Topic 6 Schema for coverage geometry and functions 

https://www.unidata.ucar.edu/software/netcdf 

IETF RFC 4627, JavaScript Object Notation (JSON), and terms `object`, `name`, `value`, `array`, `string`, `number`, and `null`. 
    
JSON-LD is defined in http://www.w3.org/TR/json-ld/.
    
A Compact URI has the form prefix:suffix.
    
The key words “MUST”, “MUST NOT”, “REQUIRED”, “SHALL”, “SHALL NOT”, “SHOULD”, “SHOULD NOT”, “RECOMMENDED”, “MAY”, and “OPTIONAL” in this document are to be interpreted as described in IETF RFC 2119.

language tag as defined in BCP 47

UTC http://www.opengis.net/def/trs/BIPM/0/UTC

ISO8601-based lexical representations

CoverageJSON media type SHALL be application/prs.coverage+json with an optional parameter profile which is a non-empty list of space-separated URIs identifying specific constraints or conventions that apply to a CoverageJSON document according to RFC6906

====
