== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== *RFC*
Request For Comment (IETF)

=== *BCP*
Best Current Practice. It may include several RFCs (IETF)

=== *Coverage*
feature that acts as a function to return values from its range for any direct position within its spatial, temporal or spatiotemporal domain (ISO19123-1)

=== *i18n object*
string in multiple languages with tags as defined in [BCP 47](http://tools.ietf.org/html/bcp47), and the value is the string in that language.
The special language tag `"und"` can be used to identify a value whose language is unknown or undetermined. (IETF BCP47)
